### ISSUE TITLE
MacOS installation error

### ISSUE THREAD

**Issue by rssample** [KeenSecurityLab/BinAbsInspector#12]
I tried using BinAbsInspector on MacOS, but got the following error:
 `BinAbsInspector.java> Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration`

But I have successfully installed Z3 using the command: brew install z3, and I can find the z3 library in /usr/local/lib. 
I don't know where I went wrong. Could you give me some advice?

**Comment by MatthewShao** [comment]
Sorry, I don't have MacOS environment for now but have some suggestions that you could try:
1. It is not suggest to install z3 with package manager as mentioned in readme, because the version mismatch may cause problems. You could try to down pre-built z3 library from https://github.com/Z3Prover/z3/releases/download/z3-4.8.15/z3-4.8.15-x64-osx-10.16.zip, unzip it and copy `./bin/*.so` to `/usr/local/lib/`.
2. If it does not work, maybe you need to build the z3 library and install by yourself according to https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang
3. If it still does not work, you could try to run it in docker.

**Comment by iweizime** [comment]
Both `libz3.dylib` and `libz3java.dylib` are needed. You can download z3 from https://github.com/Z3Prover/z3/releases or build z3 with command `CXX=clang++ CC=clang python3 scripts/mk_make.py --java --prefix=/usr/local`. Make sure `JAVA_HOME` and `JNI_HOME` are set correctly before building z3.

**Comment by leothompson2** [comment]
> I tried using BinAbsInspector on MacOS, but got the following error: `BinAbsInspector.java> Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration`
> 
> But I have successfully installed Z3 using the command: brew install z3, and I can find the z3 library in /usr/local/lib. I don't know where I went wrong. Could you give me some advice?

did you solve it?

**Comment by rssample** [comment]
> > I tried using BinAbsInspector on MacOS, but got the following error: `BinAbsInspector.java> Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration`
> > But I have successfully installed Z3 using the command: brew install z3, and I can find the z3 library in /usr/local/lib. I don't know where I went wrong. Could you give me some advice?
> 
> did you solve it?
No. The` libz3.dylib` and `libz3java.dylib` in  https://github.com/Z3Prover/z3/releases don't work. I try to build the z3 library and install by myself. But I don't know where to set the `JNI_HOME` path, I set it to the same path as `JAVA_HOME`, but it doesn't work.

if I use the command in [Z3 readme](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang), I'm going to get another error:
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [z3] Error 1
```

**Comment by KnoooW** [comment]
how about brew install z3 ?

**Comment by MatthewShao** [comment]
> > > I tried using BinAbsInspector on MacOS, but got the following error: `BinAbsInspector.java> Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration`
> > > But I have successfully installed Z3 using the command: brew install z3, and I can find the z3 library in /usr/local/lib. I don't know where I went wrong. Could you give me some advice?
> > 
> > 
> > did you solve it?
> 
> No. The` libz3.dylib` and `libz3java.dylib` in https://github.com/Z3Prover/z3/releases don't work. I try to build the z3 library and install by myself. But I don't know where to set the `JNI_HOME` path, I set it to the same path as `JAVA_HOME`, but it doesn't work.
> 
> if I use the command in [Z3 readme](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang), I'm going to get another error:
> 
> ```
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [z3] Error 1
> ```

I guest you are using a mac with M1 processor, so you need to install `arm64` instead of `x86_64`, please refer to https://github.com/Z3Prover/z3/issues/5848#issuecomment-1043170229, they also provide a prebuilt version:https://github.com/Z3Prover/z3/issues/5848#issuecomment-1093772909, no sure if it works, maybe you need to replace `./lib/com.microsoft.z3.jar` and rebuild the extension for this.

**Comment by rssample** [comment]
> > > > I tried using BinAbsInspector on MacOS, but got the following error: `BinAbsInspector.java> Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration`
> > > > But I have successfully installed Z3 using the command: brew install z3, and I can find the z3 library in /usr/local/lib. I don't know where I went wrong. Could you give me some advice?
> > > 
> > > 
> > > did you solve it?
> > 
> > 
> > No. The` libz3.dylib` and `libz3java.dylib` in https://github.com/Z3Prover/z3/releases don't work. I try to build the z3 library and install by myself. But I don't know where to set the `JNI_HOME` path, I set it to the same path as `JAVA_HOME`, but it doesn't work.
> > if I use the command in [Z3 readme](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang), I'm going to get another error:
> > ```
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > make: *** [z3] Error 1
> > ```
> 
> I guest you are using a mac with M1 processor, so you need to install `arm64` instead of `x86_64`, please refer to [Z3Prover/z3#5848 (comment)](https://github.com/Z3Prover/z3/issues/5848#issuecomment-1043170229), they also provide a prebuilt version:[Z3Prover/z3#5848 (comment)](https://github.com/Z3Prover/z3/issues/5848#issuecomment-1093772909), no sure if it works, maybe you need to replace `./lib/com.microsoft.z3.jar` and rebuild the extension for this.


My MAC is x86 architecture and my Clang version information is as follows:
```
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```

**Comment by ochimo** [comment]
FWIW I was able to get this working on an M1 Macbook as follows:

Build Z3 following instructions for [Z3 Make/Clang](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang) but be sure to specify --java when you execute mk_make.py
`python scripts/mk_make.py --java`

Copy the built libz3.dylib and libz3java.dylib to the root of your Ghidra install (where ghidraRun is located). This is necessary because of the SIP protection issue documented [here](https://github.com/Z3Prover/z3/issues/294)

Not necessarily permanent solution but gets things working.

**Comment by diablo0822** [comment]
the same error on Macos X86_64, Monterey 12.4.
Java:
java --version
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

while i try to compile z3-z3-4.8.15 by this comman : python scripts/mk_make.py --java
i got the error: zsh: command not found: python
which means that there is no python2 install in my system, and i switch to python3: python3 scripts/mk_make.py --java
python3 scripts/mk_make.py --java
opt = --java, arg =
New component: 'util'
New component: 'polynomial'
....
Component extra_cmds
Component shell
Traceback (most recent call last):
  File "/Users/carl/Downloads/z3-z3-4.8.15/scripts/mk_make.py", line 17, in <module>
    mk_auto_src()
  File "/Users/carl/Downloads/z3-z3-4.8.15/scripts/mk_util.py", line 2782, in mk_auto_src
    mk_all_install_tactic_cpps()
  File "/Users/carl/Downloads/z3-z3-4.8.15/scripts/mk_util.py", line 2889, in mk_all_install_tactic_cpps
    mk_install_tactic_cpp(cnames, c.src_dir)
  File "/Users/carl/Downloads/z3-z3-4.8.15/scripts/mk_util.py", line 2877, in mk_install_tactic_cpp
    h_files_full_path = get_header_files_for_components(component_src_dirs)
  File "/Users/carl/Downloads/z3-z3-4.8.15/scripts/mk_util.py", line 2866, in get_header_files_for_components
    h_files = filter(lambda f: f.endswith('.h') or f.endswith('.hpp'), os.listdir(component_src_dir))
FileNotFoundError: [Errno 2] No such file or directory: 'src/ast/fpa'

any ideas about this?
