### ISSUE TITLE
How to use intellij IDEA Debug source BinAbsInspector.java code?

### ISSUE THREAD

**Issue by nocbtm** [KeenSecurityLab/BinAbsInspector#16]
I want to use intellij IDEA Debug BinAbsInspector.java source code.

<img width="1956" alt="image" src="https://user-images.githubusercontent.com/37969561/164228187-e16f13d0-6a90-4dc5-903a-02aab340e363.png">

But if the first line of code fails, how do I configure the correct debug environment?
<img width="775" alt="image" src="https://user-images.githubusercontent.com/37969561/164228659-9ca17091-3322-49e7-9c43-021928f22c2c.png">

**Comment by MatthewShao** [comment]
I guess you missed the "args" in Ghidra launcher configuration. Please try to fill like this:
![image](https://user-images.githubusercontent.com/9366279/164268042-b20834d8-2b54-48f8-90d8-f9ee0e7a2f48.png)

**Comment by nocbtm** [comment]
Thank you, I know where I went wrong, I prefer debug BinAbsInspector source code with start GHidra in GUI mode, now I succeed.
<img width="1956" alt="image" src="https://user-images.githubusercontent.com/37969561/164362244-8810c6b7-6647-4f1d-9e6f-33ac1b64f205.png">
