### ISSUE TITLE
Mac下docker方式启动错误

### ISSUE THREAD

**Issue by leothompson2** [KeenSecurityLab/BinAbsInspector#19]
如下：
![image](https://user-images.githubusercontent.com/99589404/164616321-0dc176a1-5e1d-46b4-a6fe-2f5ba74802da.png)

**Comment by MatthewShao** [comment]
Please refer to https://github.com/soedinglab/hh-suite/issues/280#issuecomment-887711582, in short, you can delete `-j8` in https://github.com/KeenSecurityLab/BinAbsInspector/blob/de66de4516d60fc75137d0f0d1285ca5625c69bb/Dockerfile#L44
