### ISSUE TITLE
 inst.getFlowType allways return FALL_THROUGH

### ISSUE THREAD

**Issue by snowhax** [KeenSecurityLab/BinAbsInspector#24]
哥，同样分析/bin/ls，在创建cfg控制流图的时候有点问题

函数：
![2](https://user-images.githubusercontent.com/43437791/165050270-8ae881f5-88d7-435d-9223-618823eb85fb.PNG)

 获取后驱的时候总是返回 FALL_THROUGH
![1](https://user-images.githubusercontent.com/43437791/165050378-76f7a7bb-d814-4776-b3b2-21c94360294b.PNG)

**Comment by MatthewShao** [comment]
这个是预期结果，CFG的每个节点是`Instruction`。`XOR EBP, EBP`的flowType就是`FALL_THROUGH`。

**Comment by snowhax** [comment]
> 这个是预期结果，CFG的每个节点是`Instruction`。`XOR EBP, EBP`的flowType就是`FALL_THROUGH`。

哦 我以为是下一个 BaseBlock
