### ISSUE TITLE
can not run script

### ISSUE THREAD

**Issue by hackoflpf** [KeenSecurityLab/BinAbsInspector#34]
I use ghidra 10.1.2 ,jdk 18,z3 4.8.15.I install the extensions, then when i analysis the binary ,it says Unable to locate script class: BinAbsInspector.java,what should i do to fix this
![image](https://user-images.githubusercontent.com/23718380/167277596-6efaaf2a-eb54-47e0-839d-a031799469d4.png)

**Comment by hackoflpf** [comment]
I finally build the BinAbsInspector myself。All runs normally

**Comment by pich4ya** [comment]
exactly the same issue with the latest release.

**Comment by ipwning** [comment]
I have a same problem even though build it myself. 

Please anybody help me :(

**Comment by z0812yq** [comment]
I have a same problem 
Please anybody help me 
I used ghidra 10.1.2, java 17, z3 4.8.15

**Comment by 75ACOL** [comment]
我使用了JDK17后可以正常运行
