### ISSUE TITLE
Ghidra 10.2 安装BinAbsInspector插件的时候报错，提示版本不符合

### ISSUE THREAD

**Issue by biggermonester** [KeenSecurityLab/BinAbsInspector#36]
![image](https://user-images.githubusercontent.com/52701155/167915029-95ab3ab9-e507-4330-a948-394795f44f3a.png)

**Comment by MatthewShao** [comment]
我们提供下载的版本是适用于Ghidra 10.1.2的，目前Ghidra发布的最新版为10.1.3，请问10.2版本是哪里来的？

**Comment by biggermonester** [comment]
这个是我下载Ghidra最新源码后自己编译的，我本地的编译环境是openjdk11,vs2022,sdk10.0.19041.685
![1652325599(1)](https://user-images.githubusercontent.com/52701155/167985397-37db5fab-456b-4e1c-a893-54a3678ef15a.png)

**Comment by MatthewShao** [comment]
提供的zip包里面有一个`extension.properties`文件，你可以试试将其中`version=10.1.2` 改成对应的版本

**Comment by biggermonester** [comment]
直接修改version=10.1.2 到对应版本后能装上，但运行回报错
![image](https://user-images.githubusercontent.com/52701155/167986899-79afa007-4cdb-4bf7-93c4-200b113f3f1c.png)

**Comment by MatthewShao** [comment]
有两个解决方法：1. 下载Ghidra10.1.2的版本直接安装提供的zip包；2. 基于10.2版本重新编译，编译流程请参考wiki文档，但不保证API兼容性，可能会有其他错误

**Comment by biggermonester** [comment]
好的，我去下载个10.12版本的试试
