### ISSUE TITLE
can not choose cwe types in ghidra UI mode

### ISSUE THREAD

**Issue by hackoflpf** [KeenSecurityLab/BinAbsInspector#37]
![image](https://user-images.githubusercontent.com/23718380/168046956-e83f9778-71d3-4e27-ae3b-60b7d393d212.png)
![image](https://user-images.githubusercontent.com/23718380/168047044-640ddbba-ad34-4e49-bcd9-b718a38ba13b.png)
![image](https://user-images.githubusercontent.com/23718380/168049362-b07bd31c-c604-4914-98fe-3a4618698ce5.png)

Althouth i choose the specific cwe types，it does not work as i expected。I don't known how to fix this problem。Or should i use it in headless mode?
Besides,the results of cwe 787 check are really Outrageous。

**Comment by hackoflpf** [comment]
Oh，another question，i can't close the dialog when it was running....

**Comment by MatthewShao** [comment]
1. You can select multiple checkers with the "Ctrl" key.
2. What behavior does not fit your expectations? You can turn on the "debug" and see if a particular checker is running.
3. We had a commit recently which fixed the CWE787 false positive.

**Comment by hackoflpf** [comment]
For example,i just want to check cwe-78,but the result includes all types even i haven't choosed before,i don't known why,i build the project from source.

**Comment by MatthewShao** [comment]
I guess you are seeing a lot of cwe warnings from the `MemoryCorruption` checker. Actually we have two set of checkers, the first set is configurable, which you can find here: https://github.com/KeenSecurityLab/BinAbsInspector/blob/main/src/main/java/com/bai/checkers/CheckerManager.java#L12,
and other checkers are run "online", for example the cwe checks in `MemoryCorruption.java`, these could not config to disable for now.
