### ISSUE TITLE
Headless mode problem

### ISSUE THREAD

**Issue by pantrombka** [KeenSecurityLab/BinAbsInspector#38]
Hey, when i'm trying to execute binabsinspector in headless mode with parameters 
` "@@ -all -entry 0x180006c64 -K 50 -callStringK 3 -timeout -1 -Z3Timeout 1000"`
I got  a error:
`Exception in thread "main" ghidra.util.exception.InvalidInputException: Bad argument: -entry`

**Comment by MatthewShao** [comment]
I guess you're running against a macho file? For now we only run tests on ELF files. Though the algorithm itself should be able to work for macho files. I will be happy to take a look if you can provide the sample file.
