### ISSUE TITLE
Can BinAbsInspector analysis the libxxx.so or libxxx.a file?

### ISSUE THREAD

**Issue by diablo0822** [KeenSecurityLab/BinAbsInspector#40]
Can BinAbsInspector analysis the libxxx.so or libxxx.a file? i noticed that this tool require a main fuction as the entry, can i use it to analysis a libxxx.so or libxxx.a which without main function?
thank you

**Comment by MatthewShao** [comment]
Of cause, you can specify the entry address with `-entry` parameter
