### ISSUE TITLE
Analysis Checkers not Exposed or Missing

### ISSUE THREAD

**Issue by SaifRushdHadad** [KeenSecurityLab/BinAbsInspector#42]
Hello,

Many checks are not implemented or available for the plugin (via `-all` or `--check <>`). 
- available: 78,134,190,367,427,467,676. 
- not available: 119,125,415,416,426,476,787 

The checker manager map has a 1:1 mapping of half of the supported checks listed on the README. 
https://github.com/KeenSecurityLab/BinAbsInspector/blob/main/src/main/java/com/bai/checkers/CheckerManager.java#L10-L20

There seems to be a lot of checks that are in the MemoryCorruption bit that are tested but not exposed to the end user.
https://github.com/KeenSecurityLab/BinAbsInspector/tree/main/src/main/java/com/bai/checkers
https://github.com/KeenSecurityLab/BinAbsInspector/blob/main/src/main/java/com/bai/checkers/MemoryCorruption.java

**Comment by MatthewShao** [comment]
Yes, we have two types of checkers:
+ 78,134,190,367,427,467,676: these are offline checkers, which can be run when the analysis is finished.
+ 119,125,415,416,426,476,787: these are online checkers, which will run on-the-fly.

For the online checkers, we do not have a configuration parameter to turn it on/off, so these checkers will be run **by default**.

**Comment by SaifRushdHadad** [comment]
Thank you much for clarifying!
