### ISSUE TITLE
How could I install Z3 solver?

### ISSUE THREAD

**Issue by lightbordwin** [KeenSecurityLab/BinAbsInspector#45]
I have downloaded [z3-4.8.17-x86-win.zip](https://github.com/Z3Prover/z3/releases/download/z3-4.8.17/z3-4.8.17-x86-win.zip) and unziped it.And set the PATH environment to z3-4.8.17-x86-win\bin .But BinAbsInspector.java still tell me :Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration. How could I install z3 solver?

**Comment by MatthewShao** [comment]
The release version is supposed work with z3 4.8.15, wrong version could lead to this issue. If you want to use other versions of z3, please compile the plugin with source code.

**Comment by xinjin95** [comment]
Simply following [commands](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang) of building z3 did not solve this problem for me. You have to build to get the `libz3java.so` library which cannot be obtained from the commands. Specifically,

I had the same error: BinAbsInspector.java> Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration.

So I built z3 following the command in z3's readme file. However, after restarting ghidra and BinaryAbsInspector, I still got the problem. And the `libz3.so` was in my PATH (i.e., it's in my /usr/lib/ directory).

After investigation, I found we have to build the `libz3java.so` library  which is the z3 java library. Different from running`python scripts/mk_make.py` of the recommended [commands](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang), you need to enable the java z3 library build configuration by:
```bash
python scripts/mk_make.py --java
```
After building z3, make sure `libz3java.so` is included in your PATH.

Hope this can help those who have the same problem as me.

**Comment by guoyonglianban** [comment]
After switching to the corresponding JDK version, restart and create a new project to resolve the issue.
