### ISSUE TITLE
手动编译报错

### ISSUE THREAD

**Issue by yijiyouyu** [KeenSecurityLab/BinAbsInspector#51]
`FAILURE: Build failed with an exception.

* Where:
Build file '/data/home/wjl/ghidra_10.1.2_PUBLIC/BinAbsInspector/build.gradle' line: 18

* What went wrong:
Plugin [id: 'net.ltgt.errorprone', version: '2.0.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:2.0.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 323ms
`

**Comment by MatthewShao** [comment]
I guess this is a network issue. Please change the maven source or use a proxy. If you feel troublesome or don't know how to do that, you can just remove this dependency because it is for static analysis of our Java code.
