### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by torabi12** [KeenSecurityLab/BinAbsInspector#56]
I am using Ubuntu 22.04.1 Desktop OS and I followed the installation of BinAbsInspector strictly.
I have ghidra 10.1.2
I got the *.so files like this:
https://github.com/Z3Prover/z3/releases/download/z3-4.8.15/z3-4.8.15-x64-glibc-2.31.zip
$ unzip z3-4.8.15-x64-glibc-2.31.zip
$ cd ~/z3-4.8.15-x64-glibc-2.31/bin
$ sudo cp *.so /usr/local/lib/

I imported the ghidra_10.1.2_PUBLIC_20220420_BinAbsInspector.zip file successfully, but I get this error in ghidra:

![kép](https://user-images.githubusercontent.com/98665813/188711733-77f2a6a9-78f0-4794-8764-77ce92a70c88.png)

Tis is the java environment:
$ java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

I have no idea what to do, please help!

**Comment by MatthewShao** [comment]
I guess that's because `z3-4.8.15-x64-glibc-2.31` lib file is not compatible with ubuntu 22.04 which using glibc-2.35, you could follow the instruction here: https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang to build the z3.

**Comment by torabi12** [comment]
Thank you, I built the 4.8.15 source successfully and I have libz3.so, but the other so file for z3 solver is still missing:
![kép](https://user-images.githubusercontent.com/98665813/188800262-d2062c0e-d9da-43d6-8049-066aef4fbdb7.png)

can I get it from z3-4.8.15-x64-glibc-2.31.zip or how can I build it?

I am not a developer, I am not good in this part sorry.

**Comment by MatthewShao** [comment]
You should copy `libz3.so` and `libz3java.so` to `/usr/local/lib/`. It should work, if it still doesn't, you can try to run with docker image.

**Comment by torabi12** [comment]
I rebuilt the z3 with this command:
$ python scripts/mk_make.py --java

and I have the 2 .so files, liz3.so and libz3java.so. Both are copied to /usr/local/lib

The bad news is that the error is the same:
BinAbsInspector.java> Cannot detect z3 solver library, please check your z3 solver installation or disable z3 solver in configuration.

z3-4.8.15 is the best version to use?

**Comment by MatthewShao** [comment]
Z3-4.8.15 has been tested, other versions should work as well, but we cannot guarantee it.

**Comment by torabi12** [comment]
I put both .so files to /lib dir and the z3 issue looks like gone, I have only this:
![kép](https://user-images.githubusercontent.com/98665813/188811681-4b2eb2d3-334f-4af6-a032-9d9a6a6e3010.png)

**Comment by torabi12** [comment]
I tried it on Ubuntu 20.04.5 and on Ubuntu 18.04.6 with the same java 11 JDK but I got the same red error as above.
I built the z3 on every system, as you suggested.

Java 11 must be good for ghidra 10.1.2 as the installation page shows:
https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.1.2_build/GhidraDocs/InstallationGuide.html#Requirements

I don't know what is the problem. Docker is not good for me.

**Comment by MatthewShao** [comment]
Could you please show what binary you are running for?

**Comment by torabi12** [comment]
Hello Matthew,

I use this FW file:
https://ftp.dlink.ru/pub/Router/DIR-645/Firmware/Old/DIR645A1_FW102B08.bin

I am not sure this is the best choice. Could you give me another one which is suitable for sure?
Thank you!

**Comment by torabi12** [comment]
Thank, I am a beginner, sorry for my lack of knowledge.
Now I tried an ELF file from here:
https://github.com/JonathanSalwan/binary-samples/blob/master/elf-Linux-ARM64-bash

which is ELF:
![image](https://user-images.githubusercontent.com/98665813/189850952-848bb30c-2a89-4eb7-bbe3-5e64b5e1a4a1.png)

but I have the same red lines in the script console as I attached above.

**Comment by torabi12** [comment]
Could you give me an example ELF file which is valid for BinAbSInspector?
I would like to verify my installation. After this I think this question can be closed.

**Comment by torabi12** [comment]
Thank you for your support.
