### ISSUE TITLE
Exception in thread "main" ghidra.util.exception.InvalidInputException: /data/workspace/BinAbsInspector/test is not a valid directory or file

### ISSUE THREAD

**Issue by harry1080** [KeenSecurityLab/BinAbsInspector#59]
您好，我使用docker方式进行搭建这个程序，在分析一个elf文件的时候出现这种错误，请问大佬如何解决

![image](https://user-images.githubusercontent.com/19358692/190838903-7aa04b84-f9aa-4ad9-ad08-d1b492340313.png)

docker run -v $(pwd):/data/workspace bai "@@<script parameters>" -import test

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
INFO  Using log config file: jar:file:/opt/ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /root/.ghidra/.ghidra_10.1.2_PUBLIC/application.log (LoggingInitialization)  
INFO  Loading user preferences: /root/.ghidra/.ghidra_10.1.2_PUBLIC/preferences (Preferences)  
INFO  Class search complete (1304 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
Exception in thread "main" ghidra.util.exception.InvalidInputException: /data/workspace/BinAbsInspector/test is not a valid directory or file.
        at ghidra.app.util.headless.AnalyzeHeadless.parseOptions(AnalyzeHeadless.java:212)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:113)
        at ghidra.GhidraLauncher.launch(GhidraLauncher.java:59)
        at ghidra.Ghidra.main(Ghidra.java:47)

![image](https://user-images.githubusercontent.com/19358692/190838880-7d0116b2-4cc5-43d4-bcf5-39a7465b1f6f.png)

**Comment by kscieslinski** [comment]
Any update on this?

**Comment by MatthewShao** [comment]
@harry1080 you should replace `<script parameters>` with the actual parameter from 
![image](https://user-images.githubusercontent.com/9366279/193027218-d14d4f5f-0da0-4035-b3b6-ffed04934b06.png)
