### ISSUE TITLE
请问这个插件加载还有啥步骤？我这边尝试了加载，没有成功

### ISSUE THREAD

**Issue by harry1080** [KeenSecurityLab/BinAbsInspector#60]
![image](https://user-images.githubusercontent.com/19358692/190839079-f7826f9c-05ae-48e3-9977-cb9e80a43123.png)

**Comment by now4yreal** [comment]
Hi:

Obviously, it is because that your Ghidra version dosen't match the version of this plugin.

**Comment by harry1080** [comment]
> Hi:
> 
> Obviously, it is because that your Ghidra version dosen't match the version of this plugin.

roger,thanks
