### ISSUE TITLE
CWE数量不足是什么原因呢？

### ISSUE THREAD

**Issue by Jackey0** [KeenSecurityLab/BinAbsInspector#65]
README.md中写的CWE有下面这些，一共可以检查13个CWE类型。
![image](https://user-images.githubusercontent.com/52018740/226296520-3424f918-2c1f-4bda-a274-c0679457c05c.png)

我在命令行和GUI运行的时候都只显示了7个CWE类型。如下：
![image](https://user-images.githubusercontent.com/52018740/226296853-957fa413-045a-4422-b081-d60e5bf17980.png)

我用的ghidra版本是10.1，是什么原因呢？

**Comment by MatthewShao** [comment]
有部分checker是默认开启状态，详见：https://github.com/KeenSecurityLab/BinAbsInspector/blob/main/src/main/java/com/bai/checkers/MemoryCorruption.java#L39

**Comment by Jackey0** [comment]
thanks
