### ISSUE TITLE
在分析MIPS处理器的elf文件发生闪退

### ISSUE THREAD

**Issue by Qixiao2000** [KeenSecurityLab/BinAbsInspector#79]
![微信图片_20240606233736](https://github.com/KeenSecurityLab/BinAbsInspector/assets/111235432/29bb8608-8596-410f-b2c9-8c7ee558eb27)
你好，Windows环境下，Ghidra可正常分析MIPS处理器的elf文件，并且找到了entry地址。使用BinAbslnspector时，填入起始地址，其余参数保持默认，点击OK后，Ghidra软件闪退，请帮忙分析解决一下，谢谢

**Comment by 0gur1** [comment]
hello，请问怎么解决的呢
